version: "3.8"

services:
  nginx:
    image: nginx:1.25.4-alpine
    volumes:
      - ./back:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:80"
    depends_on:
      - db
      - php
  php:
    build:
      args:
        USER: user
        UID: 1001
      context: ./docker/php
    volumes:
      - ./back:/var/www/app
  db:
    image: postgres:16.2-alpine3.19
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"

  memcached:
    image: memcached:1.6.23-alpine
    ports:
      - "11222:11211"

  mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"
volumes:
  data:
